#!/usr/bin/ruby -w

# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will 
# be:
#
#		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not 
# exceed four million.
#

# Calculate Fibonacci sequence to k
@fib = Hash.new {|h,k| [0,1].include?(k) ? k : h[k] = h[k-1] + h[k-2]}

# return Fibonacci sequence for first n terms
def fibonacci(n)
	@fib[n]
	@fib.values.sort
end

# solution to problem 2
def problem2
	sum = n = 0
	while sum < 4000000
		n += 1
		fib = fibonacci(n)
		fib.reject! {|i| i % 2 != 0}
		sum = fib.inject {|sum,i| sum + i} unless fib.empty?
	end
	sum
end

puts "the answer is #{problem2}"
